-- public.forecasts definition

-- Drop table

-- DROP TABLE public.forecasts;

CREATE TABLE public.forecasts (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"date" date NOT NULL,
	temperature_c numeric NOT NULL,
	CONSTRAINT forecasts_pk PRIMARY KEY (id)
);