create table if not exists forecasts
(
    id            bigint generated by default as identity,
    date          date    not null,
    temperature_c numeric not null
);

alter table forecasts
    owner to postgres;

alter table forecasts
    add constraint forecasts_pk
        primary key (id);

